import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, BellRing, Check, ChevronDown, CircleAlert, ClipboardList, Factory, PackageCheck, Pill, ScanLine, ShieldCheck, ShoppingCart, Sparkles, Upload } from "lucide-react";
import Button from "@/components/ui/Button";

const plans = [
  { key: "monthly", name: "Monthly", amount: "PKR 3,500", cadence: "/ month", description: "A flexible way to get started." },
  { key: "six_months", name: "6 Months", amount: "PKR 19,000", oldAmount: "PKR 21,000", saving: "Save PKR 2,000", discount: "Save 10%", description: "A smoother operating rhythm." },
  { key: "year", name: "1 Year", amount: "PKR 37,000", oldAmount: "PKR 42,000", saving: "Save PKR 5,000", discount: "Save about 12%", description: "The strongest value for your team.", featured: true },
];

const features = [
  [PackageCheck, "Inventory clarity", "Track medicines, quantities, pricing, minimums, and batch detail in one dependable workspace."],
  [ShoppingCart, "FEFO-aware POS", "Sell eligible stock in First Expiry, First Out order with a server-side stock re-check."],
  [CircleAlert, "Expiry intelligence", "See low-stock, expiring, and expired inventory early enough to take action."],
  [Factory, "Supplier control", "Keep supplier contacts organized and connect receiving activity to inventory batches."],
  [Upload, "CSV import", "Validate and preview your existing inventory before bringing it in safely."],
  [BarChart3, "Reports that help", "Follow invoices, revenue, payment mix, product movement, and inventory exposure."],
];

const faqs = [
  ["What is Rx Assistant AI?", "A pharmacy operations workspace for inventory, batches, FEFO sales, suppliers, alerts, reports, and analytics."],
  ["Is there a free trial?", "Yes. New workspaces receive a seven-day trial created by the backend when the pharmacy account is created."],
  ["Can I import existing inventory?", "Yes. The CSV importer validates headers, quantities, prices, dates, duplicate batches, and existing records before import."],
  ["Does the POS use FEFO?", "Yes. The checkout backend re-checks stock and allocates eligible batches by earliest expiry."],
  ["How are payments handled?", "JazzCash and Meezan Bank are manual verification methods. A submitted transfer remains pending until verified."],
  ["How is pharmacy data separated?", "Each pharmacy has its own secure workspace and users only see their pharmacy's operational records."],
];

const useCases = [
  ["Pharmacy owner", "Understand inventory risk and business performance before making the next decision."],
  ["Pharmacist", "Manage batches, expiry dates, and FEFO sales with confidence at the counter."],
  ["Pharmacy staff", "Process receiving, sales, and everyday stock tasks with less searching."],
  ["Management", "Review operational records, reports, and alerts from one secure workspace."],
];

function FefoVisual() {
  return <div className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl shadow-slate-900/5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">FEFO visualized</p><h3 className="mt-2 text-2xl font-black text-slate-950">The earliest eligible batch comes first.</h3></div><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-black text-teal-700">Active</span></div><div className="mt-6 space-y-3">{[["Batch A", "15 Sep 2026", "w-full", true], ["Batch B", "20 Jan 2027", "w-4/5", false], ["Batch C", "30 Aug 2027", "w-3/5", false]].map(([batch, expiry, width, active]) => <div className={`rounded-2xl border p-3 ${active ? "border-teal-300 bg-teal-50" : "border-slate-100 bg-slate-50"}`} key={batch}><div className="flex items-center justify-between text-sm"><span className="font-black text-slate-900">{batch}</span><span className={`font-bold ${active ? "text-teal-700" : "text-slate-500"}`}>Expiry: {expiry}</span></div><div className="mt-3 h-2 rounded-full bg-slate-200"><div className={`h-full rounded-full ${active ? "bg-teal-500" : "bg-slate-300"} ${width}`} /></div>{active && <p className="mt-2 text-xs font-black text-teal-700">Selected first for eligible sale</p>}</div>)}</div><div className="mt-6 flex items-center gap-3 text-center text-xs font-black text-slate-600"><span className="flex-1 rounded-xl bg-slate-100 px-3 py-3">FEFO</span><ArrowRight size={16} className="text-teal-600" /><span className="flex-1 rounded-xl bg-teal-50 px-3 py-3 text-teal-800">Safe allocation</span></div></div>;
}

function AutomationVisual() {
  return <div className="relative rounded-[2rem] border border-slate-700 bg-slate-900 p-6 text-white shadow-2xl shadow-slate-900/20"><div className="absolute left-10 right-10 top-[4.7rem] hidden h-px bg-gradient-to-r from-teal-500/20 via-teal-400 to-teal-500/20 sm:block" /><div className="relative grid gap-3 sm:grid-cols-5">{[["01", "Inventory data"], ["02", "AI analysis"], ["03", "Risk detection"], ["04", "Smart alert"], ["05", "Action"]].map(([number, label], index) => <div className="rounded-2xl border border-slate-700 bg-slate-800 p-4" key={label}><span className="text-xs font-black text-teal-300">{number}</span><div className={`mt-5 h-2 w-2 rounded-full bg-teal-400 ${index < 4 ? "landing-pulse" : ""}`} /><p className="mt-4 text-sm font-black">{label}</p></div>)}</div><div className="mt-6 flex items-start gap-3 rounded-2xl border border-teal-400/20 bg-teal-400/10 p-4"><Sparkles size={18} className="mt-0.5 shrink-0 text-teal-300" /><div><p className="text-sm font-black text-teal-200">AI Inventory Insight</p><p className="mt-1 text-sm leading-6 text-slate-300">3 medicines are approaching their expiry threshold. Potential inventory risk: <strong className="text-white">PKR 124,500</strong>.</p></div></div></div>;
}

function MarketingExtras() {
  return <>
    <section id="problems" className="bg-slate-950 py-24 text-white sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">The everyday pressure</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Pharmacy work should not feel like detective work.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Rx Assistant brings the signals together so your team can spend less time searching and more time acting.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[[CircleAlert, "Expiry exposure", "Know which batches need attention before stock quietly becomes a loss.", "text-rose-400"], [PackageCheck, "Stockouts", "Low-stock signals help the team prioritize the next receiving or replenishment task.", "text-amber-400"], [ClipboardList, "Manual work", "Replace scattered notes and repeated checks with one dependable operating record.", "text-teal-300"]].map(([Icon, title, text, tone]) => <div className="rounded-3xl border border-slate-700 bg-slate-900 p-6" key={title}><Icon className={tone} size={24} /><p className="mt-8 text-2xl font-black">{title}</p><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></div>)}</div></div></section>
    <section id="fefo" className="bg-[#f3f8f7] py-24 sm:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Safe stock movement</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">FEFO turns expiry data into a better sale.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The platform prioritizes the earliest eligible batch, helping your counter team move stock in the right order without adding another manual decision.</p><div className="mt-7 flex items-center gap-2 text-sm font-black text-teal-800"><ShieldCheck size={17} /> Server re-checks stock at checkout</div></div><FefoVisual /></div></section>
    <section id="automation" className="bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">Intelligence, responsibly applied</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Your pharmacy, powered by automation.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Start with clean operational data. Let analysis surface risks and next actions without making claims the product cannot support.</p></div><AutomationVisual /></div></section>
    <section id="use-cases" className="bg-[#f3f8f7] py-24 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Built around your team</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">One platform, different daily needs.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{useCases.map(([title, text]) => <article className="rounded-3xl border border-white bg-white/70 p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg" key={title}><div className="h-2 w-10 rounded-full bg-teal-500" /><h3 className="mt-8 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-4">{[["Real-time", "Inventory control"], ["FEFO", "Controlled allocation"], ["Automated", "Operational alerts"], ["AI-ready", "Business insights"]].map(([eyebrow, label]) => <div className="rounded-2xl bg-white p-4" key={eyebrow}><p className="text-xs font-black uppercase text-teal-700">{eyebrow}</p><p className="mt-2 font-black text-slate-900">{label}</p></div>)}</div></div></section>
  </>;
}

function ProductVisual() {
  return <div className="relative mx-auto w-full max-w-[590px] lg:mr-0">
    <div className="absolute -inset-8 rounded-full bg-teal-400/15 blur-3xl" />
    <div className="relative rotate-[-1deg] rounded-[2rem] border border-white/15 bg-white/10 p-2 shadow-2xl backdrop-blur-sm transition duration-500 hover:rotate-0 sm:p-3">
      <div className="overflow-hidden rounded-[1.5rem] bg-slate-50">
        <div className="flex items-center justify-between bg-slate-900 px-4 py-3 text-white">
          <div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-teal-500 text-xs font-black">Rx</span><div><p className="text-xs font-black">Rx Assistant AI</p><p className="text-[10px] text-slate-400">Pharmacy workspace</p></div></div>
          <div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-rose-400" /><span className="h-2 w-2 rounded-full bg-amber-400" /><span className="h-2 w-2 rounded-full bg-emerald-400" /></div>
        </div>
        <div className="grid gap-3 p-4 sm:grid-cols-[.62fr_1.38fr]">
          <div className="rounded-xl bg-slate-900 p-3 text-slate-500"><div className="h-2 w-16 rounded bg-teal-500" /><div className="mt-7 space-y-3"><div className="h-2 w-24 rounded bg-slate-700" /><div className="h-2 w-20 rounded bg-slate-700" /><div className="h-2 w-28 rounded bg-slate-700" /></div><div className="mt-10 rounded-lg bg-teal-500/15 p-2 text-[10px] font-bold text-teal-300">Live workspace</div></div>
          <div><div className="grid grid-cols-3 gap-2">{[["PKR 248k", "Revenue", "text-teal-700"], ["18", "Low stock", "text-amber-600"], ["7", "Expiry", "text-rose-600"]].map(([value, label, tone]) => <div className="rounded-xl border border-slate-200 bg-white p-2.5" key={label}><p className={`text-sm font-black ${tone}`}>{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</p></div>)}</div><div className="mt-3 rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-black text-slate-800">Sales activity</p><span className="text-[9px] font-bold text-teal-700">Last 7 days</span></div><div className="mt-5 flex h-24 items-end gap-2">{[42, 58, 46, 78, 65, 88, 72].map((height, index) => <div key={index} style={{ height: `${height}%` }} className={`flex-1 rounded-t-md ${index === 5 ? "bg-teal-600" : "bg-teal-200"}`} />)}</div></div><div className="mt-3 flex items-center justify-between rounded-xl bg-amber-50 p-3"><div className="flex items-center gap-2"><BellRing size={15} className="text-amber-600" /><span className="text-[10px] font-bold text-slate-700">Attention queue</span></div><span className="text-[10px] font-black text-amber-700">Needs review</span></div></div>
        </div>
      </div>
    </div>
  </div>;
}

function Landing() {
  return <><div className="overflow-hidden bg-[#fbfcfb]">
    <section id="home" className="relative bg-slate-950 text-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(20,184,166,.2),transparent_30%),radial-gradient(circle_at_12%_80%,rgba(14,116,144,.16),transparent_28%)]" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-28">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-teal-400/30 bg-teal-400/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.18em] text-teal-300"><Sparkles size={14} /> Smart pharmacy management</div><h1 className="mt-7 max-w-2xl text-5xl font-black leading-[.96] tracking-[-.06em] sm:text-7xl">Run your pharmacy with <span className="text-teal-400">clarity.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Inventory, batches, FEFO sales, suppliers, alerts, and performance in one calm operating system built around pharmacy work.</p><div className="mt-9 flex flex-wrap gap-3"><Button as={Link} to="/register" size="lg" rightIcon={<ArrowRight size={18} />}>Start 7-Day Free Trial</Button><a href="#product"><Button className="border-slate-700 bg-transparent text-white hover:bg-white/10" size="lg">See how it works</Button></a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm font-bold text-slate-400"><span className="inline-flex items-center gap-2"><Check size={17} className="text-teal-400" /> No payment to start</span><span className="inline-flex items-center gap-2"><Check size={17} className="text-teal-400" /> Your own pharmacy workspace</span></div></div>
        <ProductVisual />
      </div>
    </section>

    <section className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap gap-x-8 gap-y-3 px-5 py-6 text-sm font-bold text-slate-600 sm:px-8"><span className="inline-flex items-center gap-2"><Pill size={17} className="text-teal-600" /> Pharmacy-focused</span><span className="inline-flex items-center gap-2"><ClipboardList size={17} className="text-teal-600" /> Batch-aware</span><span className="inline-flex items-center gap-2"><ShoppingCart size={17} className="text-teal-600" /> FEFO-enabled POS</span><span className="inline-flex items-center gap-2"><ShieldCheck size={17} className="text-teal-600" /> Secure workspace</span><span className="inline-flex items-center gap-2"><ScanLine size={17} className="text-teal-600" /> Built for daily use</span></div></section>

    <section id="product" className="bg-[#f3f8f7] py-24 sm:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Made for the daily details</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight text-slate-950 sm:text-5xl">Everything your pharmacy needs, in one view.</h2><p className="mt-5 text-lg leading-8 text-slate-600">From a new batch arriving at the door to the report you review at the end of the day, Rx Assistant keeps the important context connected.</p><div className="mt-8 space-y-4">{[[PackageCheck, "Know what is in stock", "Batch quantities, prices, suppliers, and expiry dates stay visible."], [ShoppingCart, "Sell with more confidence", "FEFO-aware checkout helps your team choose eligible stock in the right order."], [BarChart3, "See what needs a decision", "Clear alerts, sales history, and reports turn records into next actions."]].map(([Icon, title, text]) => <div className="flex gap-3" key={title}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-teal-700 shadow-sm"><Icon size={19} /></span><div><h3 className="font-black text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></div>)}</div></div><div className="rounded-[2rem] border border-white bg-white p-4 shadow-xl shadow-slate-900/5 sm:p-6"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">The workflow</p><p className="mt-1 text-xl font-black text-slate-950">From receiving to insight</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-700">Connected</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[Upload, "Add inventory", "Capture the batch"], [ClipboardList, "Manage batches", "Keep detail together"], [CircleAlert, "Monitor stock", "See attention early"], [ShoppingCart, "Sell with FEFO", "Dispense safely"], [ScanLine, "Track sales", "Keep an audit trail"], [BarChart3, "Understand performance", "Act on the pattern"]].map(([Icon, title, text], index) => <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4" key={title}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-teal-700 shadow-sm"><Icon size={18} /></span><div><p className="text-sm font-black text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div><span className="ml-auto text-xs font-black text-slate-300">0{index + 1}</span></div>)}</div></div></div></section>

    <section id="features" className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">The essentials, connected</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Less friction in every aisle.</h2></div><p className="max-w-sm text-sm leading-7 text-slate-600">Purpose-built capabilities for real pharmacy operations.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text], index) => <article className="group relative rounded-3xl border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-teal-300 hover:shadow-xl hover:shadow-teal-900/5" key={title}><span className="absolute right-6 top-6 text-xs font-black tracking-[.18em] text-slate-300 group-hover:text-teal-500">0{index + 1}</span><div className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-teal-700 transition group-hover:bg-teal-600 group-hover:text-white"><Icon size={22} /></div><h3 className="mt-6 max-w-[13rem] text-xl font-black tracking-tight text-slate-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="security" className="bg-teal-50 py-24 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 sm:px-8 lg:grid-cols-[.7fr_1.3fr]"><div className="relative mx-auto"><div className="absolute inset-0 rounded-full bg-teal-300/40 blur-2xl" /><div className="relative grid h-28 w-28 place-items-center rounded-[2rem] bg-teal-600 text-white shadow-xl shadow-teal-900/20"><ShieldCheck size={48} /></div></div><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Built for trust</p><h2 className="mt-3 text-3xl font-black text-slate-950 sm:text-4xl">Your pharmacy data stays in its own secure workspace.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Pharmacy users see only their pharmacy's operational data, while access decisions stay anchored in the application backend.</p></div></div></section>

    <section id="workflow" className="bg-slate-900 py-24 text-white sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">A calmer daily rhythm</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">One connected journey through the pharmacy.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{[[Upload, "Add inventory"], [ClipboardList, "Manage batches"], [CircleAlert, "Monitor expiry"], [ShoppingCart, "Sell with FEFO"], [ScanLine, "Track sales"], [BarChart3, "Understand performance"]].map(([Icon, label], index) => <div className="rounded-2xl border border-slate-700 bg-slate-800/70 p-5" key={label}><span className="text-xs font-black text-teal-300">0{index + 1}</span><Icon size={22} className="mt-8 text-teal-400" /><p className="mt-5 text-sm font-black leading-5">{label}</p></div>)}</div></div></section>

    <section id="pricing" className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Simple pricing</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Choose the pace that fits your pharmacy.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Every plan includes the complete operations workspace and starts with seven days free.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.key} className={`relative flex flex-col rounded-3xl border p-7 ${plan.featured ? "border-teal-500 bg-slate-950 text-white shadow-2xl shadow-teal-900/20 lg:-translate-y-3" : "border-slate-200 bg-white"}`}>{plan.featured && <span className="absolute -top-3 right-6 rounded-full bg-teal-500 px-3 py-1 text-xs font-black tracking-wide text-white">BEST VALUE</span>}<p className={`text-sm font-black ${plan.featured ? "text-teal-300" : "text-teal-700"}`}>{plan.name}</p><p className={`mt-4 text-sm ${plan.featured ? "text-slate-300" : "text-slate-500"}`}>{plan.description}</p><div className="mt-8"><p className="text-4xl font-black">{plan.amount}</p>{plan.oldAmount ? <p className={`mt-2 text-sm ${plan.featured ? "text-slate-400" : "text-slate-500"}`}><span className="line-through">{plan.oldAmount}</span> <span className="font-bold text-emerald-500">{plan.saving}</span></p> : <p className={`mt-2 text-sm ${plan.featured ? "text-slate-400" : "text-slate-500"}`}>{plan.cadence}</p>}</div>{plan.discount && <span className="mt-4 w-fit rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">{plan.discount}</span>}<ul className={`mt-7 space-y-3 border-t pt-6 text-sm ${plan.featured ? "border-slate-800 text-slate-200" : "border-slate-100 text-slate-600"}`}>{["Inventory and batch management", "FEFO pharmacy POS", "Suppliers, alerts, and reports", "Pharmacy-level data separation"].map((item) => <li className="flex items-center gap-2" key={item}><Check size={16} className="shrink-0 text-teal-500" />{item}</li>)}</ul><Button as={Link} to={plan.key === "monthly" ? "/register" : `/checkout?plan=${plan.key}`} variant={plan.featured ? "primary" : "secondary"} fullWidth className="mt-8">{plan.key === "monthly" ? "Start 7-Day Free Trial" : `Choose ${plan.name}`}</Button></article>)}</div></div></section>

    <section id="faq" className="bg-[#f3f8f7] py-24 sm:py-32"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-700">Questions, answered</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950">A clear start for your team.</h2></div><div className="mt-10 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white px-6">{faqs.map(([question, answer]) => <details className="group py-5" key={question}><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold text-slate-900"><span>{question}</span><ChevronDown size={18} className="shrink-0 text-teal-700 transition group-open:rotate-180" /></summary><p className="max-w-3xl pt-3 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="bg-teal-600 py-20 text-white sm:py-24"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 sm:px-8 md:flex-row md:items-center"><div><h2 className="text-3xl font-black sm:text-4xl">Ready to run your pharmacy smarter?</h2><p className="mt-3 max-w-xl text-teal-50">Start your seven-day free trial and experience a faster, clearer way to manage pharmacy operations.</p></div><div className="flex flex-wrap gap-3"><Button as={Link} to="/register" variant="secondary" size="lg">Start 7-Day Free Trial</Button><a href="#pricing"><Button className="border-white/40 bg-transparent text-white hover:bg-white/10" size="lg">View Pricing</Button></a></div></div></section>
  </div>
    <MarketingExtras />
  </>;
}

export default Landing;
