import { useEffect, useState } from "react";
import { Menu } from "lucide-react";
import { useLocation } from "react-router-dom";
import { getCurrentProfile } from "@/services/appService";
import UserMenu from "@/components/dashboard/UserMenu";
import AlertsPanel from "@/components/dashboard/AlertsPanel";
const titles = { "/dashboard": ["Dashboard", "Your pharmacy at a glance"], "/inventory": ["Inventory", "Manage medicine batches and stock"], "/suppliers": ["Suppliers", "Manage supplier contacts and receiving links"], "/sales": ["Sales / POS", "Create safe, traceable medicine sales"], "/sales/history": ["Sales history", "Review invoices and completed transactions"], "/analytics": ["Analytics", "Business performance using real records"], "/reports": ["Reports", "Preview and export operational reports"], "/settings": ["Settings", "Pharmacy profile and operational preferences"] };
function Topbar({ onMenu }) { const location = useLocation(); const [profile, setProfile] = useState(null); const [title, subtitle] = titles[location.pathname] || ["Rx Assistant", "Pharmacy operations"]; useEffect(() => { getCurrentProfile().then(setProfile).catch(() => setProfile(null)); }, []); return <header className="sticky top-0 z-20 flex h-18 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><button onClick={onMenu} className="rounded-xl p-2 text-slate-600 hover:bg-slate-100 lg:hidden" aria-label="Open navigation"><Menu size={21} /></button><div className="min-w-0"><h1 className="truncate text-lg font-extrabold text-slate-900 sm:text-xl">{title}</h1><p className="hidden truncate text-xs text-slate-500 sm:block">{subtitle}</p></div></div><div className="flex items-center gap-1 sm:gap-3"><AlertsPanel /><UserMenu profile={profile} /></div></header>; }
export default Topbar;
